/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/assets/models/scene.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Landscape(props) {
  const { nodes, materials } = useGLTF('public/assets/models/scene.glb')
  const [lightMaterial,waterMaterial] = useMemo(() => {
    return[new MeshStandardMaterial({
        
    }), new MeshStandardMaterial({color: 'blue', transparent: true, opacity: 0.5})]
  })
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.landscape_gltf.geometry} material={materials['Material.009']} />
      <mesh geometry={nodes.landscape_borders.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.trees_light.geometry} material={materials['Material.008']} />
      <mesh geometry={nodes.walls.geometry} material={nodes.walls.material} position={[0, 3, -5.109]} rotation={[Math.PI / 2, 0, 0]} scale={[5, 1, 3]} />
      <mesh geometry={nodes.water.geometry} material={materials.Water} />
      <mesh geometry={nodes.water1.geometry} material={materials.Water} />
      <mesh geometry={nodes.water2.geometry} material={materials.Water} />
      <mesh geometry={nodes.lights.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/scene.glb')
