/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/assets/models/airplane.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Airplane(props) {
  const { nodes, materials } = useGLTF('public/assets/models/airplane.glb')
  const groupRef = useRef()
  const helixmeshRef = useRef()
  return (
    <group ref={groupRef}>
    <group {...props} dispose={null}>
      <mesh geometry={nodes.supports.geometry} material={materials['Material.004']} />
      <mesh geometry={nodes.chassis.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.helix.geometry} material={materials['Material.005']} ref={helixmeshRef} />
    </group>
    </group>
  )
}

useGLTF.preload('/airplane.glb')